# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_order_system_development

test:
  <<: *default
  database: food_order_system_test

production:
  primary: &primary_production
    <<: *default
    database: food_order_system_production
    username: food_order_system
    password: <%= ENV["FOOD_ORDER_SYSTEM_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: food_order_system_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: food_order_system_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: food_order_system_production_cable
    migrations_paths: db/cable_migrate
