name: GitHub Pages Deploy with SCSS Build

on:
  push:
    branches: [ features/assignment-one ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dart Sass
      run: npm install -g sass

    - name: Compile SCSS to CSS
      run: |
        mkdir -p css
        sass scss/style.scss css/style.css

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Prepare site directory
      run: |
        mkdir -p _site
        cp index.html _site/
        cp -r css js assets pages _site/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
