name: GitHub Pages Deploy with SCSS Build

on:
  push:
    branches: [ features/assignment-one ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dart Sass
      run: npm install -g sass

    - name: Compile SCSS to CSS
      run: |
        mkdir -p css
        sass scss/style.scss css/style.css

    - name: Check compiled CSS
      run: |
        file css/style.css
        cat css/style.css

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
